/**
 * The lesson videos that ship with the site.
 *
 * Every lesson in the catalog has a short narrated video — a title card, the
 * core idea, the worked example, the practice challenge and a pointer to the
 * next lesson — generated by `npm run videos:build` from the narration scripts
 * in `content/lesson-videos/`.
 *
 * The videos are *not* published lessons: they belong to the catalog lesson
 * they explain, which is why they are stored here rather than in the owner's
 * upload list. `LessonFile` is reused for the shape because the player, the
 * access rules and the file route already understand it, and the mapping lives
 * in `lesson-media.ts`.
 *
 * This module is deliberately free of Node APIs: client components import it
 * to know whether a lesson has a video, while the bytes are served by
 * `/api/lesson-videos/[lessonId]`, which checks access first.
 */
import { LESSON_VIDEOS } from "@/content/lesson-videos";
import type { Lesson, LessonFile } from "./courses";

export interface LessonVideoEntry {
  lessonId: string;
  courseId: string;
  title: string;
  /** Length of the finished video, in seconds. */
  durationSeconds: number;
  /** Length of the narration alone, in seconds. */
  narrationSeconds: number;
  width: number;
  height: number;
  format: string;
  /** Object key in the configured storage (Supabase, or `.data/uploads`). */
  key: string;
  name: string;
  size: number;
  poster: { key: string; name: string; size: number; format: string };
  /** Chapter marks for the player, in seconds from the start. */
  chapters: { label: string; start: number }[];
  /** True when at least one slide change could not be tied to a spoken pause. */
  approximateTiming: boolean;
  voice: string;
  generatedAt: string;
}

export function lessonVideo(lessonId: string): LessonVideoEntry | null {
  return LESSON_VIDEOS[lessonId] ?? null;
}

export function lessonVideoCount(): number {
  return Object.keys(LESSON_VIDEOS).length;
}

export function totalVideoSeconds(): number {
  return Object.values(LESSON_VIDEOS).reduce((sum, entry) => sum + entry.durationSeconds, 0);
}

/**
 * The video as a lesson material, shaped exactly like an owner upload.
 *
 * `href` and `poster` point at the video routes rather than at storage: a
 * learner's access is checked before any bytes move, the same way the owner's
 * uploaded materials are gated, and the disk backend never has to expose a
 * path.
 */
export function lessonVideoFile(entry: LessonVideoEntry): LessonFile {
  return {
    id: "lesson-video",
    name: entry.name,
    size: entry.size,
    mime: entry.format,
    kind: "video",
    uploadedAt: entry.generatedAt,
    href: `/api/lesson-videos/${entry.lessonId}`,
    trimStart: 0,
    trimEnd: null,
    muted: false,
    poster: `/api/lesson-videos/${entry.lessonId}/poster`,
  };
}

/** Every lesson that has a video in the manifest, keyed by lesson id. */
export function lessonsWithVideo(lessons: Lesson[]): Lesson[] {
  return lessons.filter((lesson) => Boolean(LESSON_VIDEOS[lesson.id]));
}
