/**
 * Database schema.
 *
 * This one list is used in two ways:
 *   1. `src/lib/db.ts` runs it (idempotently) on first use, so the app can
 *      create its own tables on a fresh database.
 *   2. `npm run db:schema` prints it to `db/schema.sql`, which you can paste
 *      into the Supabase SQL editor, Neon, RDS or any Postgres host.
 *
 * `MIGRATION_STATEMENTS` below it is the companion list: idempotent reshapes
 * (adding/backfilling columns, normalizing roles, and replacing incompatible
 * constraints) that bring a database made by an older build up to this schema.
 * `ensureSchema()` runs both lists, and `db:schema` prints both, so deploying
 * the code (or pasting the SQL) is the whole upgrade. Existing application
 * rows are preserved; stale constraints may be replaced where needed.
 *
 * Everything here is plain PostgreSQL and works on Supabase, Neon, RDS or a
 * local server. No extensions are required: ids are generated by the
 * application (`randomUUID`) and stored as text, so the schema does not depend
 * on pgcrypto or on a PostgreSQL version newer than 12. Indexes and constraints are declared so the database — not the
 * application — is what guarantees unique emails and valid rows.
 *
 * `app_state` holds non-user content the owner publishes (their lesson index,
 * branding, prices). It lives here rather than in JSON files on the server's disk,
 * which is wiped on redeploy by hosts with an ephemeral filesystem.
 *
 * Deliberately denormalised: the per-learner learning record (progress,
 * invoices, activity, usage) is kept in JSONB columns next to the account row.
 * That keeps reads to a single row and matches the domain objects the app
 * already uses. If you outgrow it, split those JSONB columns into
 * `course_progress`, `lesson_progress`, `invoices` and `activity_events`
 * tables — the shapes are documented in `src/lib/store.ts`.
 */
export const SCHEMA_STATEMENTS: string[] = [

  `create table if not exists app_state (
     key        text primary key,
     value      jsonb not null,
     updated_at timestamptz not null default now()
   )`,

  `create table if not exists users (
     id                text primary key,
     email             text not null,
     name              text not null,
     password_hash     text not null,
     role              text not null default 'student' check (role in ('student', 'owner')),
     owner             boolean not null default false,
     suspended         boolean not null default false,
     subscription      jsonb not null,
     usage             jsonb not null,
     lifetime_minutes  integer not null default 0,
     progress          jsonb not null default '{}'::jsonb,
     purchases         jsonb not null default '[]'::jsonb,
     certificates      jsonb not null default '[]'::jsonb,
     invoices          jsonb not null default '[]'::jsonb,
     activity_log      jsonb not null default '[]'::jsonb,
     payment_method    jsonb not null,
     profile           jsonb not null,
     avatar            jsonb,
     last_seen_at      timestamptz,
     created_at        timestamptz not null default now(),
     updated_at        timestamptz not null default now()
   )`,

  // Emails are stored lower-cased, so a plain unique index is enough and it is
  // the database that refuses duplicates (even under concurrent sign-ups).
  `create unique index if not exists users_email_key on users (lower(email))`,

  // Exactly one owner account.
  `create unique index if not exists users_single_owner on users (owner) where owner`,

  `create index if not exists users_created_at_idx on users (created_at desc)`,

  // Invoice numbers come from a real sequence, so they stay unique even with
  // concurrent checkouts.
  `create sequence if not exists invoice_number_seq start 1007`,

  // Mobile Money / card payments, tracked from checkout to webhook.
  //
  // One row per checkout attempt, keyed by the reference we generate
  // (`CMG-…`). The row is created *before* the student is sent to the payment
  // provider, so the webhook and the return-URL verification both have
  // something idempotent to fulfil against: whichever arrives first marks the
  // row `paid` and grants the pass / course / lesson, and the other sees the
  // row is already paid and does nothing. `provider_event_id` carries the
  // provider's own event id for the same reason. Only `program` rows are
  // created now; the pass / course / lesson kinds stay valid so payments
  // already in flight can still fulfil.
  `create table if not exists payments (
     reference         text primary key,
     user_id           text not null references users(id) on delete cascade,
     kind              text not null check (kind in ('pass', 'course', 'lesson', 'program')),
     period            text check (period in ('daily', 'weekly', 'monthly')),
     course_id         text,
     lesson_id         text,
     program_id        text,
     amount            integer not null check (amount >= 0),
     currency          text not null default 'GHS',
     description       text not null,
     status            text not null default 'pending'
                       check (status in ('pending', 'paid', 'failed', 'abandoned')),
     provider          text not null default 'demo'
                       check (provider in ('demo', 'paystack')),
     phone             text,
     network           text,
     authorization_url text,
     channel           text,
     invoice_number    text,
     provider_event_id text,
     paid_at           timestamptz,
     created_at        timestamptz not null default now(),
     updated_at        timestamptz not null default now()
   )`,
  // The payments indexes live in MIGRATION_STATEMENTS, not here: a `payments`
  // table made by hand (or by an older build) may exist without our columns,
  // and `create table if not exists` skips it silently — so the columns are
  // healed first and the indexes are built only afterwards.
];

/**
 * Reshapes a database made by an older build into the schema above.
 *
 * Runs after SCHEMA_STATEMENTS on every first use (and printed after it by
 * `npm run db:schema`), so deploying the code — or pasting `db/schema.sql` —
 * is the whole upgrade. Every statement is idempotent and preserves existing
 * rows: columns are added, missing values are backfilled, roles the code
 * cannot understand are normalized, and incompatible legacy constraints are
 * replaced. No application data is dropped.
 *
 * The one retype is `payments`: its columns are aligned to the types this app
 * writes (`text` for ids and strings), because a table left by another project
 * in the same database cannot otherwise hold what a checkout produces — the
 * student sees a generic 500 and the reason is only visible in the logs. The
 * cast preserves every value; see the heal block at the end of this list.
 *
 * What this still deliberately does NOT fix, because no blind migration safely
 * can: renamed columns, wrong types anywhere other than `payments`, and
 * duplicate emails (the unique index refuses them). Those surface as a named
 * `[codemasterghana] schema statement failed …` log line instead.
 */
export const MIGRATION_STATEMENTS: string[] = [
  // Every column the code reads or writes, added if an older build never
  // created it. Inline defaults backfill pre-existing rows on the spot.
  `alter table users add column if not exists role text not null default 'member'`,
  `alter table users add column if not exists owner boolean not null default false`,
  `alter table users add column if not exists suspended boolean not null default false`,
  `alter table users add column if not exists subscription jsonb`,
  `alter table users add column if not exists usage jsonb`,
  `alter table users add column if not exists lifetime_minutes integer not null default 0`,
  `alter table users add column if not exists progress jsonb not null default '{}'::jsonb`,
  // Purchased courses and lessons (the entitlement list next to the account).
  `alter table users add column if not exists purchases jsonb not null default '[]'::jsonb`,
  // Certificates earned by finishing a course. Older accounts had none; the
  // student sees one appear the next time they open a finished course.
  `alter table users add column if not exists certificates jsonb not null default '[]'::jsonb`,
  `alter table users add column if not exists invoices jsonb not null default '[]'::jsonb`,
  `alter table users add column if not exists activity_log jsonb not null default '[]'::jsonb`,
  `alter table users add column if not exists payment_method jsonb`,
  `alter table users add column if not exists profile jsonb`,
  // The student's own profile picture: the small record (stored name, mime,
  // size, upload time) of an image kept in object storage or on disk — never
  // the bytes themselves. Nullable, because most accounts will not set one and
  // the UI falls back to the student's initials.
  `alter table users add column if not exists avatar jsonb`,
  `alter table users add column if not exists last_seen_at timestamptz`,
  `alter table users add column if not exists created_at timestamptz not null default now()`,
  `alter table users add column if not exists updated_at timestamptz not null default now()`,
  // Core identity columns. Added nullable on purpose: a legacy table
  // without them is broken in a way backfills cannot fix (emails cannot be
  // invented), and failing the whole migration over it would block the
  // columns that *can* heal.
  `alter table users add column if not exists email text`,
  `alter table users add column if not exists name text`,
  `alter table users add column if not exists password_hash text`,

  // Backfill the jsonb columns the canonical schema declares NOT NULL with
  // the exact shapes `createAccount()` writes (an empty '{}' is not enough:
  // the code reads `subscription.planId` and throws on it). Both NULL and a
  // previously backfilled '{}' are healed. Then enforce NOT NULL — the app
  // always writes these itself, so nothing new can be null in between.
  `update users set subscription = jsonb_build_object('period', 'monthly', 'price', 0, 'startedAt', to_jsonb(now()), 'expiresAt', to_jsonb(now())) where subscription is null or subscription = '{}'::jsonb`,
  // Subscriptions written by an older build describe a tier and a billing
  // cycle. They are translated here into the access pass that replaced them:
  // a paid tier that has not lapsed keeps its remaining time (as a month
  // pass), everything else is an ended pass. Purchases the student had made
  // are untouched, and the plan tier no longer gates anything.
  `update users set subscription = jsonb_build_object(
     'period', 'monthly',
     'price', 0,
     'startedAt', to_jsonb(coalesce((subscription->>'currentPeriodStart')::timestamptz, now())),
     'expiresAt', case
       when subscription->>'planId' in ('premium', 'elite')
         and (subscription->>'currentPeriodEnd') is not null
         and (subscription->>'currentPeriodEnd')::timestamptz > now()
       then to_jsonb((subscription->>'currentPeriodEnd')::timestamptz)
       else to_jsonb(now())
     end
   ) where subscription->>'expiresAt' is null`,
  `update users set usage = jsonb_build_object('periodStart', to_jsonb(now()), 'minutes', 0, 'history', (select coalesce(jsonb_agg(jsonb_build_object('date', to_char(current_date - s, 'YYYY-MM-DD'), 'count', 0) order by s desc), '[]'::jsonb) from generate_series(0, 6) s), 'creditedLessonIds', '[]'::jsonb) where usage is null or usage = '{}'::jsonb`,
  `update users set payment_method = '{"brand":"Visa","last4":"4242","provider":"demo"}'::jsonb where payment_method is null or payment_method = '{}'::jsonb`,
  `update users set profile = '{"headline":"Learning one project at a time.","track":"Full-stack developer","experience":"Just starting","weeklyGoal":180}'::jsonb where profile is null or profile = '{}'::jsonb`,
  `alter table users alter column subscription set not null`,
  `alter table users alter column usage set not null`,
  `alter table users alter column payment_method set not null`,
  `alter table users alter column profile set not null`,
  // Legacy tables may allow NULL where the canonical schema does not; the
  // code reads these raw, so normalize before anything loads a row.
  `update users set owner = false where owner is null`,
  `update users set suspended = false where suspended is null`,
  `update users set lifetime_minutes = 0 where lifetime_minutes is null`,

  // There are two roles: 'student' and 'owner' (the teacher). The owner-flagged
  // row is the owner; every other account — including accounts that held
  // administrator access under an older build — becomes a student. Nothing is
  // lost: an administrator's learning record, purchases and invoices stay on
  // the account, and the owner can grant access from the console.
  // The legacy check allows only ('member', 'admin'), so it is dropped before
  // the rows are rewritten — an update to 'owner' would be rejected otherwise.
  `alter table users drop constraint if exists users_role_check`,
  `update users set role = 'owner' where owner is true and role is distinct from 'owner'`,
  `update users set role = 'student' where role is null or role not in ('student', 'owner')`,
  `alter table users add constraint users_role_check check (role in ('student', 'owner'))`,

  // app_state gets the same treatment as users.
  `alter table app_state add column if not exists value jsonb`,
  `update app_state set value = '{}'::jsonb where value is null`,
  `alter table app_state alter column value set not null`,
  `alter table app_state add column if not exists updated_at timestamptz not null default now()`,

  // A `payments` table made by hand (or by an older build) may already exist
  // with fewer columns — `create table if not exists` skips it silently, and
  // building the indexes below would then fail with `column … does not
  // exist`. So every column is added here first. All added nullable, so the
  // healing itself can never fail on rows that are already there; the app
  // always writes complete rows, and pre-existing foreign rows are simply
  // never matched by a checkout reference.
  `alter table payments add column if not exists reference text`,
  `alter table payments add column if not exists user_id text`,
  `alter table payments add column if not exists kind text`,
  `alter table payments add column if not exists period text`,
  `alter table payments add column if not exists course_id text`,
  `alter table payments add column if not exists lesson_id text`,
  `alter table payments add column if not exists program_id text`,
  // The `kind` check from older builds does not know `program`. Drop-then-add
  // keeps this idempotent: on every run the old check (if any) goes away and
  // the current one is enforced. `not valid` skips re-validating whatever a
  // hand-made table already holds — the check still guards every new row.
  `alter table payments drop constraint if exists payments_kind_check`,
  `alter table payments add constraint payments_kind_check check (kind in ('pass', 'course', 'lesson', 'program')) not valid`,
  `alter table payments add column if not exists amount integer`,
  `alter table payments add column if not exists currency text`,
  `alter table payments add column if not exists description text`,
  `alter table payments add column if not exists status text`,
  `alter table payments add column if not exists provider text`,
  `alter table payments add column if not exists phone text`,
  `alter table payments add column if not exists network text`,
  `alter table payments add column if not exists authorization_url text`,
  `alter table payments add column if not exists channel text`,
  `alter table payments add column if not exists invoice_number text`,
  `alter table payments add column if not exists provider_event_id text`,
  `alter table payments add column if not exists paid_at timestamptz`,
  `alter table payments add column if not exists created_at timestamptz`,
  `alter table payments add column if not exists updated_at timestamptz`,
  // Indexes last, once every column they reference is guaranteed to exist.
  `create index if not exists payments_user_idx on payments (user_id, created_at desc)`,
  `create index if not exists payments_status_idx on payments (status, created_at desc)`,
  `create unique index if not exists payments_event_key on payments (provider_event_id) where provider_event_id is not null`,

  // ---------------------------------------------------------------------------
  // Payments: align a table that came from somewhere else.
  //
  // A `payments` table that this app did not create — one left by an older
  // project in the same database, or a paste from a Supabase-style schema —
  // can have the right *names* and the wrong *types*, and `create table if not
  // exists` plus the `add column` list above will never notice. The failure it
  // causes is invisible: `checkout` compares `user_id`, PostgreSQL refuses the
  // comparison (`42883 operator does not exist: text = uuid` in the teacher
  // console), the row is never written (`22P02 invalid input syntax for type
  // uuid` on a text account id), and the student sees only
  // "The checkout could not be started."
  //
  // So the columns this app writes are aligned to the types it writes: text
  // for every id, reference and string column. Existing values are cast, never
  // dropped — a UUID stored as text is the same value, and it is the format
  // the app has always written. A foreign key on such a column has to go
  // first (PostgreSQL cannot retype a column an FK is built on). The next
  // migration also checks text columns: an old payments.user_id FK can point
  // at a different app's accounts table even when its type already matches.
  // Every step is best-effort: a column that cannot be converted is left
  // alone and logged, so a heal can never keep the app from starting.
  // ---------------------------------------------------------------------------
  `do $$
declare
  column_to_fix record;
  attached_key record;
begin
  for column_to_fix in
    select column_name
      from information_schema.columns
     where table_schema = current_schema()
       and table_name = 'payments'
       and column_name in ('reference', 'user_id', 'kind', 'period', 'course_id', 'lesson_id',
                           'program_id', 'description', 'status', 'provider', 'currency', 'phone',
                           'network', 'authorization_url', 'channel', 'invoice_number', 'provider_event_id')
       -- Anything that is not plain text, including varchar(8) (which would
       -- silently reject a CMG-… reference) and enum types (which accept only
       -- the labels they were born with).
       and data_type <> 'text'
  loop
    begin
      for attached_key in
        select conname from pg_constraint
         where conrelid = 'payments'::regclass
           and contype = 'f'
           and (select attnum from pg_attribute
                 where attrelid = 'payments'::regclass
                   and attname = column_to_fix.column_name and not attisdropped) = any(conkey)
      loop
        execute format('alter table payments drop constraint %I', attached_key.conname);
        raise warning '[codemasterghana] dropped foreign key % on payments.% (a text id cannot satisfy it)', attached_key.conname, column_to_fix.column_name;
      end loop;
      execute format('alter table payments alter column %I type text using %I::text', column_to_fix.column_name, column_to_fix.column_name);
      raise warning '[codemasterghana] payments.% aligned to text', column_to_fix.column_name;
    exception when others then
      raise warning '[codemasterghana] could not align payments.% to text: %', column_to_fix.column_name, sqlerrm;
    end;
  end loop;
end $$`,

  // Retire foreign keys left by another application's `payments` table. A
  // particularly common case is `payments.user_id` being text but still
  // referencing that application's `accounts(id)`: type healing above skips
  // it, and every new checkout then fails with 23503 even though the student
  // exists in this app's `users` table. Keep only the intended single-column
  // user_id -> users.id relationship. `NOT VALID` preserves older/orphaned
  // payment rows while PostgreSQL still checks every new checkout.
  `do $heal$
declare
  payment_user_attnum smallint;
  users_id_attnum smallint;
  keep_user_fk boolean := false;
  attached_key record;
begin
  select attnum into payment_user_attnum
    from pg_attribute
   where attrelid = 'payments'::regclass
     and attname = 'user_id'
     and not attisdropped;
  select attnum into users_id_attnum
    from pg_attribute
   where attrelid = 'users'::regclass
     and attname = 'id'
     and not attisdropped;

  for attached_key in
    select conname, conkey, confrelid, confkey
      from pg_constraint
     where conrelid = 'payments'::regclass
       and contype = 'f'
  loop
    if payment_user_attnum is not null
       and users_id_attnum is not null
       and attached_key.conkey = array[payment_user_attnum]::smallint[]
       and attached_key.confrelid = 'users'::regclass
       and attached_key.confkey = array[users_id_attnum]::smallint[] then
      keep_user_fk := true;
    else
      begin
        execute format('alter table payments drop constraint %I', attached_key.conname);
        raise warning '[codemasterghana] dropped stale payments foreign key % (only payments.user_id -> users.id is supported)', attached_key.conname;
      exception when others then
        raise warning '[codemasterghana] could not drop stale payments foreign key %: %', attached_key.conname, sqlerrm;
      end;
    end if;
  end loop;

  if payment_user_attnum is not null and users_id_attnum is not null and not keep_user_fk then
    begin
      execute 'alter table payments add constraint payments_user_id_fkey foreign key (user_id) references users(id) on delete cascade not valid';
      raise notice '[codemasterghana] added payments.user_id -> users.id foreign key (not validated for legacy rows)';
    exception when others then
      raise warning '[codemasterghana] could not add payments.user_id -> users.id foreign key: %', sqlerrm;
    end;
  end if;
exception when others then
  raise warning '[codemasterghana] payments foreign key cleanup skipped: %', sqlerrm;
end $heal$`,

  // Rules left over from the table's previous life reject the values this app
  // writes — a `status` check that only knows 'succeeded', a `provider` check
  // that never heard of 'paystack'. They are dropped by *definition*, not by
  // name, because a hand-made table rarely uses the names we would guess, and
  // the rules this app expects are put back. Both halves are best-effort:
  // every step is wrapped so that a table which cannot take a rule is left
  // without it (and logged) rather than stopping the app from starting.
  //
  // Added as `not valid`, like every check in these migrations: rows that are
  // already there are never re-checked, and every rule tolerates NULL so that
  // touching an old row (stamping `updated_at`, marking it paid) cannot fail.
  `do $heal$
declare
  stale_rule record;
  wanted_rule record;
begin
  -- One guard around the whole pass: if anything here fails (a table whose
  -- catalogue entry cannot even be read), the app still starts, and the
  -- warning says which constraint was being handled.
  begin
  for stale_rule in
    select conname
      from pg_constraint
     where conrelid = 'payments'::regclass
       and contype = 'c'
       and conname <> 'payments_kind_check'
       and pg_get_constraintdef(oid) ~* '\\y(kind|status|provider|period|amount|currency)\\y'
  loop
    begin
      execute format('alter table payments drop constraint %I', stale_rule.conname);
      raise warning '[codemasterghana] dropped stale payments rule %', stale_rule.conname;
    exception when others then
      raise warning '[codemasterghana] could not drop payments rule %: %', stale_rule.conname, sqlerrm;
    end;
  end loop;

  for wanted_rule in
    select * from (values
      ('payments_status_check',   $rule$status is null or status in ('pending', 'paid', 'failed', 'abandoned')$rule$),
      ('payments_provider_check', $rule$provider is null or provider in ('demo', 'paystack')$rule$),
      ('payments_period_check',   $rule$period is null or period in ('daily', 'weekly', 'monthly')$rule$),
      ('payments_amount_check',   $rule$amount is null or amount >= 0$rule$),
      ('payments_currency_check', $rule$currency is null or currency = 'GHS'$rule$)
    ) as rules(name, definition)
  loop
    begin
      execute format('alter table payments add constraint %I check (%s) not valid', wanted_rule.name, wanted_rule.definition);
    exception when others then
      raise warning '[codemasterghana] could not add payments rule %: %', wanted_rule.name, sqlerrm;
    end;
  end loop;
  exception when others then
    raise warning '[codemasterghana] payments rule cleanup skipped: %', sqlerrm;
  end;
end $heal$`,

  // A column the app never fills, but the old table declares NOT NULL, would
  // reject every new row (23502) — with nothing in the app able to satisfy it.
  // Not-null is dropped on those columns (data is untouched), leaving the
  // primary/unique keys and anything with a default alone.
  `do $$
declare
  legacy_column record;
begin
  for legacy_column in
    select column_name
      from information_schema.columns
     where table_schema = current_schema()
       and table_name = 'payments'
       and is_nullable = 'NO'
       and column_default is null
       and column_name not in ('reference', 'user_id', 'kind', 'period', 'course_id', 'lesson_id',
                               'program_id', 'amount', 'currency', 'description', 'status', 'provider',
                               'phone', 'network', 'authorization_url', 'channel', 'invoice_number',
                               'provider_event_id', 'paid_at', 'created_at', 'updated_at')
       and column_name not in (
         select attribute.attname
           from pg_index index_definition
           join pg_attribute attribute
             on attribute.attrelid = index_definition.indrelid
            and attribute.attnum = any(index_definition.indkey)
          where index_definition.indrelid = 'payments'::regclass
            and (index_definition.indisprimary or index_definition.indisunique)
       )
  loop
    begin
      execute format('alter table payments alter column %I drop not null', legacy_column.column_name);
      raise warning '[codemasterghana] dropped NOT NULL on legacy payments column % (this app never fills it)', legacy_column.column_name;
    exception when others then
      raise warning '[codemasterghana] could not drop NOT NULL on payments.%: %', legacy_column.column_name, sqlerrm;
    end;
  end loop;
end $$`,
];

/** Rows in `users` as the database sees them. */
export interface UserRow {
  id: string;
  email: string;
  name: string;
  password_hash: string;
  role: string;
  owner: boolean;
  suspended: boolean;
  subscription: unknown;
  usage: unknown;
  lifetime_minutes: number;
  progress: unknown;
  purchases: unknown;
  certificates: unknown;
  invoices: unknown;
  activity_log: unknown;
  payment_method: unknown;
  profile: unknown;
  avatar: unknown;
  created_at: Date | string;
  updated_at: Date | string;
}
