/**
 * Database schema.
 *
 * This one list is used in two ways:
 *   1. `src/lib/db.ts` runs it (idempotently) on first use, so the app can
 *      create its own tables on a fresh database.
 *   2. `npm run db:schema` prints it to `db/schema.sql`, which you can paste
 *      into the Supabase SQL editor, Neon, RDS or any Postgres host.
 *
 * `MIGRATION_STATEMENTS` below it is the companion list: additive reshapes
 * (`ADD COLUMN IF NOT EXISTS`, backfills, role normalization) that bring a
 * database made by an older build up to this schema. `ensureSchema()` runs
 * both lists, and `db:schema` prints both, so deploying the code (or pasting
 * the SQL) is the whole upgrade — no manual ALTERs, and never a drop.
 *
 * Everything here is plain PostgreSQL and works on Supabase, Neon, RDS or a
 * local server. No extensions are required: ids are generated by the
 * application (`randomUUID`) and stored as text, so the schema does not depend
 * on pgcrypto or on a PostgreSQL version newer than 12. Indexes and constraints are declared so the database — not the
 * application — is what guarantees unique emails and valid rows.
 *
 * `app_state` holds non-user content the owner publishes (their lesson index and
 * branding). It lives here rather than in JSON files on the server's disk,
 * which is wiped on redeploy by hosts with an ephemeral filesystem.
 *
 * Deliberately denormalised: the per-learner learning record (progress,
 * invoices, activity, usage) is kept in JSONB columns next to the account row.
 * That keeps reads to a single row and matches the domain objects the app
 * already uses. If you outgrow it, split those JSONB columns into
 * `course_progress`, `lesson_progress`, `invoices` and `activity_events`
 * tables — the shapes are documented in `src/lib/store.ts`.
 */
export const SCHEMA_STATEMENTS: string[] = [

  `create table if not exists app_state (
     key        text primary key,
     value      jsonb not null,
     updated_at timestamptz not null default now()
   )`,

  `create table if not exists users (
     id                text primary key,
     email             text not null,
     name              text not null,
     password_hash     text not null,
     role              text not null default 'member' check (role in ('member', 'admin')),
     owner             boolean not null default false,
     suspended         boolean not null default false,
     subscription      jsonb not null,
     usage             jsonb not null,
     lifetime_minutes  integer not null default 0,
     progress          jsonb not null default '{}'::jsonb,
     invoices          jsonb not null default '[]'::jsonb,
     activity_log      jsonb not null default '[]'::jsonb,
     payment_method    jsonb not null,
     profile           jsonb not null,
     last_seen_at      timestamptz,
     created_at        timestamptz not null default now(),
     updated_at        timestamptz not null default now()
   )`,

  // Emails are stored lower-cased, so a plain unique index is enough and it is
  // the database that refuses duplicates (even under concurrent sign-ups).
  `create unique index if not exists users_email_key on users (lower(email))`,

  // Exactly one owner account.
  `create unique index if not exists users_single_owner on users (owner) where owner`,

  `create index if not exists users_created_at_idx on users (created_at desc)`,

  // Invoice numbers come from a real sequence, so they stay unique even with
  // concurrent checkouts.
  `create sequence if not exists invoice_number_seq start 1007`,
];

/**
 * Reshapes a database made by an older build into the schema above.
 *
 * Runs after SCHEMA_STATEMENTS on every first use (and printed after it by
 * `npm run db:schema`), so deploying the code — or pasting `db/schema.sql` —
 * is the whole upgrade. Every statement is idempotent and additive only:
 * columns are added (never renamed, retyped or dropped), missing values are
 * backfilled, and roles the code cannot understand are normalized. Existing
 * rows always survive.
 *
 * What this deliberately does NOT fix, because no blind migration safely can:
 * columns with the wrong *type*, renamed columns, and duplicate emails (the
 * unique index refuses them). Those surface as a named
 * `[codemasterghana] schema statement failed …` log line instead.
 */
export const MIGRATION_STATEMENTS: string[] = [
  // Every column the code reads or writes, added if an older build never
  // created it. Inline defaults backfill pre-existing rows on the spot.
  `alter table users add column if not exists role text not null default 'member'`,
  `alter table users add column if not exists owner boolean not null default false`,
  `alter table users add column if not exists suspended boolean not null default false`,
  `alter table users add column if not exists subscription jsonb`,
  `alter table users add column if not exists usage jsonb`,
  `alter table users add column if not exists lifetime_minutes integer not null default 0`,
  `alter table users add column if not exists progress jsonb not null default '{}'::jsonb`,
  `alter table users add column if not exists invoices jsonb not null default '[]'::jsonb`,
  `alter table users add column if not exists activity_log jsonb not null default '[]'::jsonb`,
  `alter table users add column if not exists payment_method jsonb`,
  `alter table users add column if not exists profile jsonb`,
  `alter table users add column if not exists last_seen_at timestamptz`,
  `alter table users add column if not exists created_at timestamptz not null default now()`,
  `alter table users add column if not exists updated_at timestamptz not null default now()`,
  // Core identity columns. Added nullable on purpose: a legacy table
  // without them is broken in a way backfills cannot fix (emails cannot be
  // invented), and failing the whole migration over it would block the
  // columns that *can* heal.
  `alter table users add column if not exists email text`,
  `alter table users add column if not exists name text`,
  `alter table users add column if not exists password_hash text`,

  // Backfill the jsonb columns the canonical schema declares NOT NULL with
  // the exact shapes `createAccount()` writes (an empty '{}' is not enough:
  // the code reads `subscription.planId` and throws on it). Both NULL and a
  // previously backfilled '{}' are healed. Then enforce NOT NULL — the app
  // always writes these itself, so nothing new can be null in between.
  `update users set subscription = jsonb_build_object('planId', 'free', 'cycle', 'monthly', 'cancelAtPeriodEnd', false, 'pendingPlanId', null, 'currentPeriodStart', to_jsonb(now()), 'currentPeriodEnd', to_jsonb(now() + interval '30 days')) where subscription is null or subscription = '{}'::jsonb`,
  `update users set usage = jsonb_build_object('periodStart', to_jsonb(now()), 'minutes', 0, 'history', (select coalesce(jsonb_agg(jsonb_build_object('date', to_char(current_date - s, 'YYYY-MM-DD'), 'count', 0) order by s desc), '[]'::jsonb) from generate_series(0, 6) s), 'creditedLessonIds', '[]'::jsonb) where usage is null or usage = '{}'::jsonb`,
  `update users set payment_method = '{"brand":"Visa","last4":"4242","provider":"demo"}'::jsonb where payment_method is null or payment_method = '{}'::jsonb`,
  `update users set profile = '{"headline":"Learning one project at a time.","track":"Full-stack developer","experience":"Just starting","weeklyGoal":180}'::jsonb where profile is null or profile = '{}'::jsonb`,
  `alter table users alter column subscription set not null`,
  `alter table users alter column usage set not null`,
  `alter table users alter column payment_method set not null`,
  `alter table users alter column profile set not null`,
  // Legacy tables may allow NULL where the canonical schema does not; the
  // code reads these raw, so normalize before anything loads a row.
  `update users set owner = false where owner is null`,
  `update users set suspended = false where suspended is null`,
  `update users set lifetime_minutes = 0 where lifetime_minutes is null`,

  // The code only understands 'member' and 'admin'. Owner-flagged rows are
  // administrators even when a legacy schema stored a different word
  // ('owner', 'student', ...); anything else unknown becomes a member.
  // Re-promote from /admin afterwards if a legacy word meant admin to you.
  `update users set role = 'admin' where owner is true and role is distinct from 'admin'`,
  `update users set role = 'member' where role is null or role not in ('member', 'admin')`,
  `alter table users drop constraint if exists users_role_check`,
  `alter table users add constraint users_role_check check (role in ('member', 'admin'))`,

  // app_state gets the same treatment as users.
  `alter table app_state add column if not exists value jsonb`,
  `update app_state set value = '{}'::jsonb where value is null`,
  `alter table app_state alter column value set not null`,
  `alter table app_state add column if not exists updated_at timestamptz not null default now()`,
];

/** Rows in `users` as the database sees them. */
export interface UserRow {
  id: string;
  email: string;
  name: string;
  password_hash: string;
  role: string;
  owner: boolean;
  suspended: boolean;
  subscription: unknown;
  usage: unknown;
  lifetime_minutes: number;
  progress: unknown;
  invoices: unknown;
  activity_log: unknown;
  payment_method: unknown;
  profile: unknown;
  created_at: Date | string;
  updated_at: Date | string;
}
