-- codemasterghana — database schema
-- Generated by `npm run db:schema` from src/lib/schema.ts (do not edit by hand).
--
-- Run this once against your database (Supabase SQL editor, psql, Neon console).
-- Every statement is idempotent, so re-running it is safe.

create table if not exists app_state (
     key        text primary key,
     value      jsonb not null,
     updated_at timestamptz not null default now()
   );

create table if not exists users (
     id                text primary key,
     email             text not null,
     name              text not null,
     password_hash     text not null,
     role              text not null default 'student' check (role in ('student', 'owner')),
     owner             boolean not null default false,
     suspended         boolean not null default false,
     subscription      jsonb not null,
     usage             jsonb not null,
     lifetime_minutes  integer not null default 0,
     progress          jsonb not null default '{}'::jsonb,
     purchases         jsonb not null default '[]'::jsonb,
     certificates      jsonb not null default '[]'::jsonb,
     invoices          jsonb not null default '[]'::jsonb,
     activity_log      jsonb not null default '[]'::jsonb,
     payment_method    jsonb not null,
     profile           jsonb not null,
     avatar            jsonb,
     last_seen_at      timestamptz,
     created_at        timestamptz not null default now(),
     updated_at        timestamptz not null default now()
   );

create unique index if not exists users_email_key on users (lower(email));

create unique index if not exists users_single_owner on users (owner) where owner;

create index if not exists users_created_at_idx on users (created_at desc);

create sequence if not exists invoice_number_seq start 1007;

create table if not exists payments (
     reference         text primary key,
     user_id           text not null references users(id) on delete cascade,
     kind              text not null check (kind in ('pass', 'course', 'lesson', 'program')),
     period            text check (period in ('daily', 'weekly', 'monthly')),
     course_id         text,
     lesson_id         text,
     program_id        text,
     amount            integer not null check (amount >= 0),
     currency          text not null default 'GHS',
     description       text not null,
     status            text not null default 'pending'
                       check (status in ('pending', 'paid', 'failed', 'abandoned')),
     provider          text not null default 'demo'
                       check (provider in ('demo', 'paystack')),
     phone             text,
     network           text,
     authorization_url text,
     channel           text,
     invoice_number    text,
     provider_event_id text,
     paid_at           timestamptz,
     created_at        timestamptz not null default now(),
     updated_at        timestamptz not null default now()
   );

-- ---------------------------------------------------------------------------
-- Migrations: reshape a database made by an older build (additive only).
-- The app runs these itself on first request; they are printed here so a
-- manual paste heals a stale database the same way. Safe to re-run.
-- ---------------------------------------------------------------------------

alter table users add column if not exists role text not null default 'member';

alter table users add column if not exists owner boolean not null default false;

alter table users add column if not exists suspended boolean not null default false;

alter table users add column if not exists subscription jsonb;

alter table users add column if not exists usage jsonb;

alter table users add column if not exists lifetime_minutes integer not null default 0;

alter table users add column if not exists progress jsonb not null default '{}'::jsonb;

alter table users add column if not exists purchases jsonb not null default '[]'::jsonb;

alter table users add column if not exists certificates jsonb not null default '[]'::jsonb;

alter table users add column if not exists invoices jsonb not null default '[]'::jsonb;

alter table users add column if not exists activity_log jsonb not null default '[]'::jsonb;

alter table users add column if not exists payment_method jsonb;

alter table users add column if not exists profile jsonb;

alter table users add column if not exists avatar jsonb;

alter table users add column if not exists last_seen_at timestamptz;

alter table users add column if not exists created_at timestamptz not null default now();

alter table users add column if not exists updated_at timestamptz not null default now();

alter table users add column if not exists email text;

alter table users add column if not exists name text;

alter table users add column if not exists password_hash text;

update users set subscription = jsonb_build_object('period', 'monthly', 'price', 0, 'startedAt', to_jsonb(now()), 'expiresAt', to_jsonb(now())) where subscription is null or subscription = '{}'::jsonb;

update users set subscription = jsonb_build_object(
     'period', 'monthly',
     'price', 0,
     'startedAt', to_jsonb(coalesce((subscription->>'currentPeriodStart')::timestamptz, now())),
     'expiresAt', case
       when subscription->>'planId' in ('premium', 'elite')
         and (subscription->>'currentPeriodEnd') is not null
         and (subscription->>'currentPeriodEnd')::timestamptz > now()
       then to_jsonb((subscription->>'currentPeriodEnd')::timestamptz)
       else to_jsonb(now())
     end
   ) where subscription->>'expiresAt' is null;

update users set usage = jsonb_build_object('periodStart', to_jsonb(now()), 'minutes', 0, 'history', (select coalesce(jsonb_agg(jsonb_build_object('date', to_char(current_date - s, 'YYYY-MM-DD'), 'count', 0) order by s desc), '[]'::jsonb) from generate_series(0, 6) s), 'creditedLessonIds', '[]'::jsonb) where usage is null or usage = '{}'::jsonb;

update users set payment_method = '{"brand":"Visa","last4":"4242","provider":"demo"}'::jsonb where payment_method is null or payment_method = '{}'::jsonb;

update users set profile = '{"headline":"Learning one project at a time.","track":"Full-stack developer","experience":"Just starting","weeklyGoal":180}'::jsonb where profile is null or profile = '{}'::jsonb;

alter table users alter column subscription set not null;

alter table users alter column usage set not null;

alter table users alter column payment_method set not null;

alter table users alter column profile set not null;

update users set owner = false where owner is null;

update users set suspended = false where suspended is null;

update users set lifetime_minutes = 0 where lifetime_minutes is null;

alter table users drop constraint if exists users_role_check;

update users set role = 'owner' where owner is true and role is distinct from 'owner';

update users set role = 'student' where role is null or role not in ('student', 'owner');

alter table users add constraint users_role_check check (role in ('student', 'owner'));

alter table app_state add column if not exists value jsonb;

update app_state set value = '{}'::jsonb where value is null;

alter table app_state alter column value set not null;

alter table app_state add column if not exists updated_at timestamptz not null default now();

alter table payments add column if not exists reference text;

alter table payments add column if not exists user_id text;

alter table payments add column if not exists kind text;

alter table payments add column if not exists period text;

alter table payments add column if not exists course_id text;

alter table payments add column if not exists lesson_id text;

alter table payments add column if not exists program_id text;

alter table payments drop constraint if exists payments_kind_check;

alter table payments add constraint payments_kind_check check (kind in ('pass', 'course', 'lesson', 'program')) not valid;

alter table payments add column if not exists amount integer;

alter table payments add column if not exists currency text;

alter table payments add column if not exists description text;

alter table payments add column if not exists status text;

alter table payments add column if not exists provider text;

alter table payments add column if not exists phone text;

alter table payments add column if not exists network text;

alter table payments add column if not exists authorization_url text;

alter table payments add column if not exists channel text;

alter table payments add column if not exists invoice_number text;

alter table payments add column if not exists provider_event_id text;

alter table payments add column if not exists paid_at timestamptz;

alter table payments add column if not exists created_at timestamptz;

alter table payments add column if not exists updated_at timestamptz;

create index if not exists payments_user_idx on payments (user_id, created_at desc);

create index if not exists payments_status_idx on payments (status, created_at desc);

create unique index if not exists payments_event_key on payments (provider_event_id) where provider_event_id is not null;

do $$
declare
  column_to_fix record;
  attached_key record;
begin
  for column_to_fix in
    select column_name
      from information_schema.columns
     where table_schema = current_schema()
       and table_name = 'payments'
       and column_name in ('reference', 'user_id', 'kind', 'period', 'course_id', 'lesson_id',
                           'program_id', 'description', 'status', 'provider', 'currency', 'phone',
                           'network', 'authorization_url', 'channel', 'invoice_number', 'provider_event_id')
       -- Anything that is not plain text, including varchar(8) (which would
       -- silently reject a CMG-… reference) and enum types (which accept only
       -- the labels they were born with).
       and data_type <> 'text'
  loop
    begin
      for attached_key in
        select conname from pg_constraint
         where conrelid = 'payments'::regclass
           and contype = 'f'
           and conkey = array[(select attnum from pg_attribute
                                where attrelid = 'payments'::regclass
                                  and attname = column_to_fix.column_name and not attisdropped)]
      loop
        execute format('alter table payments drop constraint %I', attached_key.conname);
        raise warning '[codemasterghana] dropped foreign key % on payments.% (a text id cannot satisfy it)', attached_key.conname, column_to_fix.column_name;
      end loop;
      execute format('alter table payments alter column %I type text using %I::text', column_to_fix.column_name, column_to_fix.column_name);
      raise warning '[codemasterghana] payments.% aligned to text', column_to_fix.column_name;
    exception when others then
      raise warning '[codemasterghana] could not align payments.% to text: %', column_to_fix.column_name, sqlerrm;
    end;
  end loop;
end $$;

do $heal$
declare
  stale_rule record;
  wanted_rule record;
begin
  -- One guard around the whole pass: if anything here fails (a table whose
  -- catalogue entry cannot even be read), the app still starts, and the
  -- warning says which constraint was being handled.
  begin
  for stale_rule in
    select conname
      from pg_constraint
     where conrelid = 'payments'::regclass
       and contype = 'c'
       and conname <> 'payments_kind_check'
       and pg_get_constraintdef(oid) ~* '\y(kind|status|provider|period|amount|currency)\y'
  loop
    begin
      execute format('alter table payments drop constraint %I', stale_rule.conname);
      raise warning '[codemasterghana] dropped stale payments rule %', stale_rule.conname;
    exception when others then
      raise warning '[codemasterghana] could not drop payments rule %: %', stale_rule.conname, sqlerrm;
    end;
  end loop;

  for wanted_rule in
    select * from (values
      ('payments_status_check',   $rule$status is null or status in ('pending', 'paid', 'failed', 'abandoned')$rule$),
      ('payments_provider_check', $rule$provider is null or provider in ('demo', 'paystack')$rule$),
      ('payments_period_check',   $rule$period is null or period in ('daily', 'weekly', 'monthly')$rule$),
      ('payments_amount_check',   $rule$amount is null or amount >= 0$rule$),
      ('payments_currency_check', $rule$currency is null or currency = 'GHS'$rule$)
    ) as rules(name, definition)
  loop
    begin
      execute format('alter table payments add constraint %I check (%s) not valid', wanted_rule.name, wanted_rule.definition);
    exception when others then
      raise warning '[codemasterghana] could not add payments rule %: %', wanted_rule.name, sqlerrm;
    end;
  end loop;
  exception when others then
    raise warning '[codemasterghana] payments rule cleanup skipped: %', sqlerrm;
  end;
end $heal$;

do $$
declare
  legacy_column record;
begin
  for legacy_column in
    select column_name
      from information_schema.columns
     where table_schema = current_schema()
       and table_name = 'payments'
       and is_nullable = 'NO'
       and column_default is null
       and column_name not in ('reference', 'user_id', 'kind', 'period', 'course_id', 'lesson_id',
                               'program_id', 'amount', 'currency', 'description', 'status', 'provider',
                               'phone', 'network', 'authorization_url', 'channel', 'invoice_number',
                               'provider_event_id', 'paid_at', 'created_at', 'updated_at')
       and column_name not in (
         select attribute.attname
           from pg_index index_definition
           join pg_attribute attribute
             on attribute.attrelid = index_definition.indrelid
            and attribute.attnum = any(index_definition.indkey)
          where index_definition.indrelid = 'payments'::regclass
            and (index_definition.indisprimary or index_definition.indisunique)
       )
  loop
    begin
      execute format('alter table payments alter column %I drop not null', legacy_column.column_name);
      raise warning '[codemasterghana] dropped NOT NULL on legacy payments column % (this app never fills it)', legacy_column.column_name;
    exception when others then
      raise warning '[codemasterghana] could not drop NOT NULL on payments.%: %', legacy_column.column_name, sqlerrm;
    end;
  end loop;
end $$;

