/**
 * The teacher's welcome video for each course — generated by `npm run videos:build`.
 *
 * Keyed by course slug. The scripts that produced them are in
 * `content/course-videos/`, and the files live in the configured storage,
 * served through `/api/course-videos/[slug]` so access is checked first.
 */
import type { CourseVideoEntry } from "@/lib/course-videos";

export const COURSE_VIDEOS: Record<string, CourseVideoEntry> = {};
