/**
 * The lesson videos that ship with the site — generated by `npm run videos:build`.
 *
 * One entry per lesson: the file the player streams (through the app's own
 * storage, so access is checked before a byte is served), the poster the
 * browser shows before playback, and the chapter marks. The narration scripts
 * that produced these are in `content/lesson-videos/`; the videos themselves
 * live in the configured storage (Supabase, or `.data/uploads` on disk), not
 * in this repository.
 *
 * Regenerate rather than edit: `npm run videos:build -- --all --force`.
 */
import type { LessonVideoEntry } from "@/lib/lesson-videos";

export const LESSON_VIDEOS: Record<string, LessonVideoEntry> = {
  "how-the-web-works": {
    "lessonId": "how-the-web-works",
    "courseId": "web-foundations",
    "title": "How the web works",
    "durationSeconds": 122.08,
    "narrationSeconds": 91.48,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__how-the-web-works.mp4",
    "name": "How the web works — video walkthrough.mp4",
    "size": 3143075,
    "poster": {
      "key": "lessonvideo__how-the-web-works--poster.jpg",
      "name": "How the web works — poster.jpg",
      "size": 52355,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 17.76
      },
      {
        "label": "Worked example",
        "start": 49.16
      },
      {
        "label": "Your turn",
        "start": 90.48
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:54:55.230Z"
  },
  "html-document": {
    "lessonId": "html-document",
    "courseId": "web-foundations",
    "title": "Your first HTML document",
    "durationSeconds": 117.84,
    "narrationSeconds": 84.04,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__html-document.mp4",
    "name": "Your first HTML document — video walkthrough.mp4",
    "size": 3039780,
    "poster": {
      "key": "lessonvideo__html-document--poster.jpg",
      "name": "Your first HTML document — poster.jpg",
      "size": 49873,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 13.4
      },
      {
        "label": "Worked example",
        "start": 41.31
      },
      {
        "label": "Your turn",
        "start": 86.05
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:54:54.203Z"
  },
  "semantic-accessible-html": {
    "lessonId": "semantic-accessible-html",
    "courseId": "web-foundations",
    "title": "Semantic & accessible HTML",
    "durationSeconds": 118.31,
    "narrationSeconds": 84.51,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__semantic-accessible-html.mp4",
    "name": "Semantic & accessible HTML — video walkthrough.mp4",
    "size": 2992861,
    "poster": {
      "key": "lessonvideo__semantic-accessible-html--poster.jpg",
      "name": "Semantic & accessible HTML — poster.jpg",
      "size": 48605,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 14.47
      },
      {
        "label": "Worked example",
        "start": 42.91
      },
      {
        "label": "Your turn",
        "start": 84.37
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:55:37.159Z"
  },
  "css-foundations": {
    "lessonId": "css-foundations",
    "courseId": "web-foundations",
    "title": "CSS foundations",
    "durationSeconds": 113.73,
    "narrationSeconds": 79.93,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__css-foundations.mp4",
    "name": "CSS foundations — video walkthrough.mp4",
    "size": 2925082,
    "poster": {
      "key": "lessonvideo__css-foundations--poster.jpg",
      "name": "CSS foundations — poster.jpg",
      "size": 42438,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 13.43
      },
      {
        "label": "Worked example",
        "start": 39.78
      },
      {
        "label": "Your turn",
        "start": 83.77
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:55:37.250Z"
  },
  "flexbox-grid": {
    "lessonId": "flexbox-grid",
    "courseId": "web-foundations",
    "title": "Layouts with Flexbox & Grid",
    "durationSeconds": 109.03,
    "narrationSeconds": 75.23,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__flexbox-grid.mp4",
    "name": "Layouts with Flexbox & Grid — video walkthrough.mp4",
    "size": 2766938,
    "poster": {
      "key": "lessonvideo__flexbox-grid--poster.jpg",
      "name": "Layouts with Flexbox & Grid — poster.jpg",
      "size": 49044,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 11.93
      },
      {
        "label": "Worked example",
        "start": 39.35
      },
      {
        "label": "Your turn",
        "start": 80.74
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:56:17.476Z"
  },
  "responsive-design": {
    "lessonId": "responsive-design",
    "courseId": "web-foundations",
    "title": "Responsive design",
    "durationSeconds": 108.95,
    "narrationSeconds": 75.15,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__responsive-design.mp4",
    "name": "Responsive design — video walkthrough.mp4",
    "size": 2717626,
    "poster": {
      "key": "lessonvideo__responsive-design--poster.jpg",
      "name": "Responsive design — poster.jpg",
      "size": 43210,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 13.34
      },
      {
        "label": "Worked example",
        "start": 39.61
      },
      {
        "label": "Your turn",
        "start": 78.97
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:56:16.861Z"
  },
  "publish-portfolio": {
    "lessonId": "publish-portfolio",
    "courseId": "web-foundations",
    "title": "Ship your portfolio",
    "durationSeconds": 102.79,
    "narrationSeconds": 68.99,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__publish-portfolio.mp4",
    "name": "Ship your portfolio — video walkthrough.mp4",
    "size": 2523093,
    "poster": {
      "key": "lessonvideo__publish-portfolio--poster.jpg",
      "name": "Ship your portfolio — poster.jpg",
      "size": 41930,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 10.13
      },
      {
        "label": "Worked example",
        "start": 32.73
      },
      {
        "label": "Your turn",
        "start": 71.81
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:56:55.287Z"
  },
  "what-computers-do": {
    "lessonId": "what-computers-do",
    "courseId": "computer-science-essentials",
    "title": "What computers actually do",
    "durationSeconds": 120.29,
    "narrationSeconds": 86.49,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__what-computers-do.mp4",
    "name": "What computers actually do — video walkthrough.mp4",
    "size": 2938657,
    "poster": {
      "key": "lessonvideo__what-computers-do--poster.jpg",
      "name": "What computers actually do — poster.jpg",
      "size": 54126,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 15.97
      },
      {
        "label": "Worked example",
        "start": 46.43
      },
      {
        "label": "Your turn",
        "start": 89.83
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:58:06.602Z"
  },
  "binary-data": {
    "lessonId": "binary-data",
    "courseId": "computer-science-essentials",
    "title": "Bits, bytes & data",
    "durationSeconds": 115.51,
    "narrationSeconds": 81.71,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__binary-data.mp4",
    "name": "Bits, bytes & data — video walkthrough.mp4",
    "size": 2714426,
    "poster": {
      "key": "lessonvideo__binary-data--poster.jpg",
      "name": "Bits, bytes & data — poster.jpg",
      "size": 46453,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 13.71
      },
      {
        "label": "Worked example",
        "start": 40.58
      },
      {
        "label": "Your turn",
        "start": 84.76
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:58:04.576Z"
  },
  "logic-algorithms": {
    "lessonId": "logic-algorithms",
    "courseId": "computer-science-essentials",
    "title": "Logic & algorithms",
    "durationSeconds": 108.8,
    "narrationSeconds": 75,
    "width": 1280,
    "height": 720,
    "format": "video/mp4",
    "key": "lessonvideo__logic-algorithms.mp4",
    "name": "Logic & algorithms — video walkthrough.mp4",
    "size": 2674172,
    "poster": {
      "key": "lessonvideo__logic-algorithms--poster.jpg",
      "name": "Logic & algorithms — poster.jpg",
      "size": 43167,
      "format": "image/jpeg"
    },
    "chapters": [
      {
        "label": "Introduction",
        "start": 0
      },
      {
        "label": "The idea",
        "start": 10.53
      },
      {
        "label": "Worked example",
        "start": 35.56
      },
      {
        "label": "Your turn",
        "start": 77.85
      }
    ],
    "approximateTiming": false,
    "voice": "voice-00",
    "generatedAt": "2026-10-07T03:58:29.154Z"
  }
};
