/**
 * Prints the database schema to stdout.
 *
 *   npm run db:schema > db/schema.sql
 *
 * Paste the result into the Supabase SQL editor (or any Postgres client) to
 * create the tables by hand instead of letting the app create them.
 */
import { SCHEMA_STATEMENTS } from "../src/lib/schema";

const header = [
  "-- codemasterghana — database schema",
  "-- Generated by `npm run db:schema` from src/lib/schema.ts (do not edit by hand).",
  "--",
  "-- Run this once against your database (Supabase SQL editor, psql, Neon console).",
  "-- Every statement is idempotent, so re-running it is safe.",
  "",
  "",
];

console.log(header.join("\n") + SCHEMA_STATEMENTS.map((statement) => `${statement};\n`).join("\n"));
