/**
 * Prints the database schema to stdout.
 *
 *   npm run db:schema > db/schema.sql
 *
 * Paste the result into the Supabase SQL editor (or any Postgres client) to
 * create the tables by hand instead of letting the app create them. The first
 * section creates; the second reshapes databases made by older builds. Every
 * statement is idempotent, so re-running the whole file is safe.
 */
import { MIGRATION_STATEMENTS, SCHEMA_STATEMENTS } from "../src/lib/schema";

const header = [
  "-- codemasterghana — database schema",
  "-- Generated by `npm run db:schema` from src/lib/schema.ts (do not edit by hand).",
  "--",
  "-- Run this once against your database (Supabase SQL editor, psql, Neon console).",
  "-- Every statement is idempotent, so re-running it is safe.",
  "",
  "",
];

const migrateHeader = [
  "-- ---------------------------------------------------------------------------",
  "-- Migrations: reshape a database made by an older build (data-preserving).",
  "-- The app runs these itself on first request; they are printed here so a",
  "-- manual paste heals a stale database the same way. Safe to re-run.",
  "-- ---------------------------------------------------------------------------",
  "",
  "",
];

const creates = SCHEMA_STATEMENTS.map((statement) => `${statement};\n`).join("\n");
const migrates = MIGRATION_STATEMENTS.map((statement) => `${statement};\n`).join("\n");

console.log(header.join("\n") + creates + "\n" + migrateHeader.join("\n") + migrates);
